feat: Integrate with Famaf-Resources-Manager
FAMAF-resources/1_1C-Analisis_Matematico_I-FAMAF pull request #2
Opened 2023-08-07 03:13 UTC by AgustinMDominguez

2023-08-07 03:25 UTC, shirosweets requested changes
Actualiazar el submodulo de examenes viejos, debe tener el nombre ExamenesViejos/

2023-08-07 03:34 UTC, shirosweets requested changes
Corroborar que el action del update de check ✅

2023-08-07 19:27 UTC, shirosweets approved these changes

2023-08-07 19:27 UTC, shirosweets requested changes

2023-08-07 19:27 UTC, shirosweets commented on .gitmodules
> +[submodule "ExamenesViejos_AnalisisMatematico1_Computacion_FaMAF"]
Modificar a ExamenesViejos

2023-08-08 19:59 UTC, IvanRenison approved these changes

2023-08-08 23:36 UTC, shirosweets approved these changes

2023-08-08 23:36 UTC, merged